version: '3.4'
# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  frontend:
    image: angular
    container_name: Angular
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 4200:80
    depends_on: 
      - backend

  backend:
    container_name: dotnet-api
    build:
      context: backend
      dockerfile: ./Dockerfile
    ports:
      - 5001:5001
    depends_on:
      - database  

  database:
    build:
      context: ./database
      dockerfile: ./Dockerfile
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db-data: