version: '3.4'

services:
  frontend:
    image: angular
    container_name: Angular
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 4200:80
    depends_on: 
      - backend

  backend:
    image: dotnet
    container_name: Dotnet
    networks:
      - apitraining
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - 12287:12287
    depends_on: 
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTIONS_DEFAULT=server=database;database=training;uid=root;pwd=Password123;

  database:
    image: mysql:8.0
    container_name: mysqldb
    networks:
      - apitraining
    environment:
      - MYSQL_ROOT_PASSWORD=Password123
      - MYSQL_DATABASE=training
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./api/docker-files/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro

volumes:
  db-data:

networks:
  apitraining: