# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  backend:
    image: backend
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 12287:12287
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=training;User=root;Password=Password123;


  db:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=Password123
      - MYSQL_DATABASE=training
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./docker-files/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro

volumes:
  db-data:
